# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 5
comments: true
# Styling
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: true

kramdown:
  use_coderay: true
  coderay_line_numbers: # Disable line numbers in code snippets

assets:
  js_compressor:  yui
  css_compressor: sass
